apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-mock-server-config
  namespace: dynamic-mock-server
  labels:
    app: dynamic-mock-server
data:
  # Server Configuration
  PORT: "8080"
  API_PREFIX: "/api"
  NODE_ENV: "production"
  
  # Storage Configuration
  STORAGE_TYPE: "file"  # Change to 'postgresql' or 'mongodb' for database storage
  
  # OpenTelemetry Configuration
  ENABLE_OTEL: "false"  # Set to "true" to enable metrics
  OTEL_SERVICE_NAME: "dynamic-mock-server"
  OTEL_SERVICE_VERSION: "1.0.0-mvp"
  PROMETHEUS_PORT: "9464"
  PROMETHEUS_ENDPOINT: "/metrics"
  
  # Tracing Configuration (Optional)
  ENABLE_TRACING: "false"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
  
  # Analytics Configuration
  ENABLE_ANALYTICS: "true"
  ANALYTICS_RETENTION_DAYS: "30"
  
  # Security Configuration
  ENABLE_CORS: "true"
  ENABLE_HELMET: "true"
  ENABLE_SECURITY: "true"
  
  # Logging Configuration
  LOG_DEV_REQUESTS: "false"
