apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-mock-server
  namespace: dynamic-mock-server
  labels:
    app: dynamic-mock-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamic-mock-server
  labels:
    app: dynamic-mock-server
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-mock-server
  labels:
    app: dynamic-mock-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynamic-mock-server
subjects:
- kind: ServiceAccount
  name: dynamic-mock-server
  namespace: dynamic-mock-server
