apiVersion: v1
kind: Secret
metadata:
  name: dynamic-mock-server-secrets
  namespace: dynamic-mock-server
  labels:
    app: dynamic-mock-server
type: Opaque
data:
  # PostgreSQL Configuration (Base64 encoded)
  # To encode: echo -n "your-password" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # 'postgres' encoded
  POSTGRES_USER: cG9zdGdyZXM=     # 'postgres' encoded
  
  # MongoDB Configuration (Base64 encoded)
  MONGO_USER: bW9uZ28=            # 'mongo' encoded
  MONGO_PASSWORD: bW9uZ28=        # 'mongo' encoded
  
  # Database URLs (will be constructed in deployment)
  # DATABASE_URL and MONGODB_URL will be set via environment variables

---
# Example for external database secrets
# Create this manually with your actual credentials
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: dynamic-mock-server
  labels:
    app: dynamic-mock-server
type: Opaque
stringData:
  # Uncomment and set these for external databases
  # postgres-host: "your-postgres-host"
  # postgres-port: "5432"
  # postgres-user: "your-username"
  # postgres-password: "your-password"
  # postgres-db: "dynamic_mock_server"
  # mongo-host: "your-mongo-host"
  # mongo-port: "27017"
  # mongo-user: "your-username" 
  # mongo-password: "your-password"
  # mongo-db: "dynamic_mock_server"
