{{- if or .Values.config.database.mongodb.uri .Values.config.database.postgresql.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamic-mock-server.secretName" . }}
  labels:
    {{- include "dynamic-mock-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.database.mongodb.uri }}
  MONGODB_URI: {{ .Values.config.database.mongodb.uri | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.database.postgresql.username }}
  POSTGRES_USERNAME: {{ .Values.config.database.postgresql.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.database.postgresql.password }}
  POSTGRES_PASSWORD: {{ .Values.config.database.postgresql.password | b64enc | quote }}
  {{- end }}
{{- end }}
